In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [3]:
data = pd.read_csv('data/google_places.csv', index_col=0)
data.head()

,place_name,rating,total_number_of_ratings,price_level,address,city,zip_code
place_id,,,,,,,
ChIJleWegJHTD4gRsIMGm3IjUcM,yolk - test kitchen,4.4,180.0,2.0,1767 n milwaukee ave,chicago,60647
ChIJI1dehI0xDogRRkvKIpUspHM,las asadas restaurant,4.0,166.0,2.0,3834 w 47th st,chicago,60632-4136
ChIJBRuLGC_MD4gRfUVkzaQBIZk,mini palapita,4.3,342.0,1.0,4968 n elston ave,chicago,60630
ChIJ-auSyWItDogRQwUqcwljejE,crazy bird chicken,4.7,67.0,NaN,1160 w grand ave,chicago,60642-5837
ChIJIYRFg7IsDogRAW0zLguKL-A,redhead piano bar,4.2,989.0,2.0,16 w ontario st,chicago,60654

In [4]:
data.shape

(13006, 7)

In [6]:
data[data.price_level.isna()].shape

(5079, 7)

In [7]:
data[data.rating.isna()].shape

(728, 7)

In [16]:
data["rating"].unique

<bound method Series.unique of place_id
ChIJleWegJHTD4gRsIMGm3IjUcM    4.4
ChIJI1dehI0xDogRRkvKIpUspHM    4.0
ChIJBRuLGC_MD4gRfUVkzaQBIZk    4.3
ChIJ-auSyWItDogRQwUqcwljejE    4.7
ChIJIYRFg7IsDogRAW0zLguKL-A    4.2
                              ...
ChIJIVSzGQ3nEYgR8nZhwaBQ9ZM    3.6
ChIJ5fNghEVMDogR4UWYi3iHLPE    NaN
ChIJtf1ZQfzqEYgR9gh_2CPqkNE    4.0
ChIJ6a1jjZssDogR3PQwtmza-vs    3.5
ChIJubeVEQrTD4gRVKoy9DuCqsQ    NaN
Name: rating, Length: 13006, dtype: float64>

In [17]:
data.reset_index(level=0,inplace=True)
data.head()

,place_id,place_name,rating,total_number_of_ratings,price_level,address,city,zip_code
0,ChIJleWegJHTD4gRsIMGm3IjUcM,yolk - test kitchen,4.4,180.0,2.0,1767 n milwaukee ave,chicago,60647
1,ChIJI1dehI0xDogRRkvKIpUspHM,las asadas restaurant,4.0,166.0,2.0,3834 w 47th st,chicago,60632-4136
2,ChIJBRuLGC_MD4gRfUVkzaQBIZk,mini palapita,4.3,342.0,1.0,4968 n elston ave,chicago,60630
3,ChIJ-auSyWItDogRQwUqcwljejE,crazy bird chicken,4.7,67.0,NaN,1160 w grand ave,chicago,60642-5837
4,ChIJIYRFg7IsDogRAW0zLguKL-A,redhead piano bar,4.2,989.0,2.0,16 w ontario st,chicago,60654

In [22]:
data[data.city == 'london']

,place_id,place_name,rating,total_number_of_ratings,price_level,address,city,zip_code
2313,ChIJkbk0TvsQdkgRf-Bzbmzb7C0,wing tai restaurant,4.0,571.0,2.0,395 edgware rd,london,nw2 6ln
5362,ChIJ-5WkAyAFdkgRIrEdoX2CpXU,tozi,4.5,953.0,3.0,8 gillingham st,london,sw1v 1hj
6031,ChIJsz4-b0AFdkgRmaEzfghxSIY,walton street,NaN,NaN,NaN,walton st,london,NaN
6985,ChIJL1PqC4wcdkgRdwLj45QtnkU,mangal turkish pizza,4.6,72.0,1.0,27 stoke newington rd,london,n16 8bj
9390,ChIJ74DrmWgEdkgRmsDo0R0P2Ts,carioca - brazilian cuisine (brixton),4.1,160.0,NaN,25-27 market row,london,sw9 8lb
11134,ChIJ61CLYvjxLogRJoxRljVsB2Y,villa cornelia,4.4,87.0,NaN,142 kent st,london,n6a 1l3

In [12]:
pd.read_pickle("violations_after_change.pickle")#['Description'].values

    Code                                        Description
0      1  PERSON IN CHARGE PRESENT, DEMONSTRATES KNOWLED...
11     2  CITY OF CHICAGO FOOD SERVICE SANITATION CERTIF...
22     3  MANAGEMENT, FOOD EMPLOYEE AND CONDITIONAL EMPL...
41     5  PROCEDURES FOR RESPONDING TO VOMITING AND DIAR...
52     6   PROPER EATING, TASTING, DRINKING, OR TOBACCO USE
57     7            NO DISCHARGE FROM EYES, NOSE, AND MOUTH
58     8                      HANDS CLEAN & PROPERLY WASHED
59     9  NO BARE HAND CONTACT WITH RTE FOOD OR A PRE-AP...
1     10  ADEQUATE HANDWASHING SINKS PROPERLY SUPPLIED A...
2     11                 FOOD OBTAINED FROM APPROVED SOURCE
3     12                FOOD RECEIVED AT PROPER TEMPERATURE
4     13      FOOD IN GOOD CONDITION, SAFE, & UNADULTERATED
5     14  REQUIRED RECORDS AVAILABLE: SHELLSTOCK TAGS, P...
6     15                       FOOD SEPARATED AND PROTECTED
7     16         FOOD-CONTACT SURFACES: CLEANED & SANITIZED
8     17  PROPER DISPOSITION OF RETURNED, PREVIOUSLY SER...
9     18                 PROPER COOKING TIME & TEMPERATURES
10    19        PROPER REHEATING PROCEDURES FOR HOT HOLDING
12    20                PROPER COOLING TIME AND TEMPERATURE
13    21                    PROPER HOT HOLDING TEMPERATURES
14    22                   PROPER COLD HOLDING TEMPERATURES
15    23                PROPER DATE MARKING AND DISPOSITION
16    24  TIME AS A PUBLIC HEALTH CONTROL; PROCEDURES & ...
17    25  CONSUMER ADVISORY PROVIDED FOR RAW/UNDERCOOKED...
18    26  PASTEURIZED FOODS USED; PROHIBITED FOODS NOT O...
19    27         FOOD ADDITIVES: APPROVED AND PROPERLY USED
20    28  TOXIC SUBSTANCES PROPERLY IDENTIFIED, STORED, ...
21    29  COMPLIANCE WITH VARIANCE/SPECIALIZED PROCESS/H...
23    30               PASTEURIZED EGGS USED WHERE REQUIRED
24    31                   WATER & ICE FROM APPROVED SOURCE
25    32  VARIANCE OBTAINED FOR SPECIALIZED PROCESSING M...
26    33  PROPER COOLING METHODS USED; ADEQUATE EQUIPMEN...
27    35                      APPROVED THAWING METHODS USED
28    36                   THERMOMETERS PROVIDED & ACCURATE
29    37          FOOD PROPERLY LABELED; ORIGINAL CONTAINER
30    38            INSECTS, RODENTS, & ANIMALS NOT PRESENT
31    39  CONTAMINATION PREVENTED DURING FOOD PREPARATIO...
32    40                               PERSONAL CLEANLINESS
33    41              WIPING CLOTHS: PROPERLY USED & STORED
34    43                   IN-USE UTENSILS: PROPERLY STORED
35    44  UTENSILS, EQUIPMENT & LINENS: PROPERLY STORED,...
36    45  SINGLE-USE/SINGLE-SERVICE ARTICLES: PROPERLY S...
37    46                               GLOVES USED PROPERLY
38    47  FOOD & NON-FOOD CONTACT SURFACES CLEANABLE, PR...
39    48  WAREWASHING FACILITIES: INSTALLED, MAINTAINED ...
40    49               NON-FOOD/FOOD CONTACT SURFACES CLEAN
42    50      HOT & COLD WATER AVAILABLE; ADEQUATE PRESSURE
43    51        PLUMBING INSTALLED; PROPER BACKFLOW DEVICES
44    52             SEWAGE & WASTE WATER PROPERLY DISPOSED
45    53  TOILET FACILITIES: PROPERLY CONSTRUCTED, SUPPL...
46    54  GARBAGE & REFUSE PROPERLY DISPOSED; FACILITIES...
47    55  PHYSICAL FACILITIES INSTALLED, MAINTAINED & CLEAN
48    56  ADEQUATE VENTILATION & LIGHTING; DESIGNATED AR...
49    57      ALL FOOD EMPLOYEES HAVE FOOD HANDLER TRAINING
50    58                      ALLERGEN TRAINING AS REQUIRED
51    59   PREVIOUS PRIORITY FOUNDATION VIOLATION CORRECTED
53    60                  PREVIOUS CORE VIOLATION CORRECTED
54    61  SUMMARY REPORT DISPLAYED AND VISIBLE TO THE PU...
55    62         COMPLIANCE WITH CLEAN INDOOR AIR ORDINANCE
56    63                         REMOVAL OF SUSPENSION SIGN